=== RabiEddin/xml_sports_2023/XML-FinalProject-KimDoyoon-21011682.dtd
<!ELEMENT Sports (Matches, Teams, Players)>
<!ATTLIST Sports category CDATA #REQUIRED>

<!ELEMENT Matches (match+)>
<!ELEMENT match (match_info, match_result, match_statistics)>
<!ATTLIST match match_no ID #REQUIRED>
<!-- match_no의 데이터 타입 CDATA -> ID 로 변경 -->

<!ELEMENT match_info (info, date)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date week CDATA #REQUIRED>

<!ELEMENT match_result (Winner, Loser)>
<!ELEMENT Winner (team_name, manager, strategy, starting_list, substitutes)>
<!ELEMENT Loser (team_name, manager, strategy, starting_list, substitutes)>
<!ELEMENT team_name (#PCDATA)>
<!ATTLIST team_name team_info IDREF #REQUIRED>
<!ELEMENT manager (#PCDATA)>
<!ELEMENT strategy (#PCDATA)>
<!ELEMENT starting_list (match_player+)>
<!ELEMENT match_player EMPTY>
<!ENTITY % match_player_info
    'num CDATA #REQUIRED
    position CDATA #REQUIRED
    goal CDATA #IMPLIED
    own_goal CDATA #IMPLIED
    captain (yes|no) "no"'>
<!ATTLIST match_player %match_player_info; >

<!ELEMENT substitutes (match_player*)>
<!ATTLIST match_player replaced_num CDATA #IMPLIED>

<!ELEMENT match_statistics (score, Possession, Shots_on_target, Shots)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT Possession (#PCDATA)>
<!ELEMENT Shots_on_target (#PCDATA)>
<!ELEMENT Shots (#PCDATA)>

<!ELEMENT Teams (team+)>
<!ELEMENT team (team_basicinfo, team_statistics, player_roster)>
<!ATTLIST team team_no ID #REQUIRED>

<!ELEMENT team_basicinfo (Team_name, League)>
<!ELEMENT Team_name (#PCDATA)>
<!ELEMENT League (#PCDATA)>

<!ELEMENT team_statistics (league_ranking, point, rate, rate, rate)>
<!ELEMENT league_ranking (#PCDATA)>
<!ELEMENT point (#PCDATA)>
<!ELEMENT rate (#PCDATA)>
<!ATTLIST rate outcome (win|draw|lose) #REQUIRED>

<!ELEMENT player_roster (player+)>
<!ELEMENT player EMPTY>
<!ATTLIST player player_info IDREF #REQUIRED>

<!ELEMENT Players (Player+)>
<!ELEMENT Player (Player_basicinfo, Player_statistics, Player_career)>
<!ATTLIST Player Player_id ID #REQUIRED>

<!ELEMENT Player_basicinfo (Player_name, Position, Age, Nationality, SNS?)>
<!ELEMENT Player_name (#PCDATA)>
<!ELEMENT Position (#PCDATA)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT Nationality (#PCDATA)>
<!ELEMENT SNS EMPTY>
<!ATTLIST SNS href CDATA #REQUIRED>

<!ELEMENT Player_statistics EMPTY>
<!ENTITY % Player_statistics_info
    'Appearances CDATA "0"
    Clean_sheets CDATA "0"
    Goals CDATA "0"
    Assists CDATA "0"'>
<!ATTLIST Player_statistics %Player_statistics_info;>

<!ELEMENT Player_career (Player_team, Player_num)>
<!ELEMENT Player_team (#PCDATA)>
<!ELEMENT Player_num (#PCDATA)>

=== RabiEddin/xml_sports_2023/XML-FinalProject-KimDoyoon-21011682-XSD & DTD.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE Sports SYSTEM "XML-FinalProject-KimDoyoon-21011682.dtd">

<!--Sports element - attribute type -> category 변경!!!-->
<!--team element 아래에 있는 rate element - attribute type -> outcome으로 수정-->
<!--위 2가지 내용에 기반하여 dtd 파일도 수정함.-->
<!--2023/11/14 match_info element 내에 있는 date 형식 변환(ex. 2023.10.29 -> 2023-10-29)-->
<!--element 내에 있는 데이터의 불필요한 앞뒤 공백을 지움-->
<!--추가된 namespace에 따라 해당 namespace에 해당하는 element 앞에 prefix 추가-->
<!--그 외 element 내에 있는 데이터 상에서 필요없는 공백도 삭제 진행함-->

<Sports category="soccer"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.matches.org XML-FinalProject-KimDoyoon-21011682.xsd"
        xmlns="http://www.matches.org"
        xmlns:tms="http://www.Teams.org"
        xmlns:ply="http://www.Players.org">
    <Matches>
        <match match_no="M1">
            <match_info>
                <info>MCI vs MUN</info>
                <date week = "10">2023-10-29</date>
            </match_info>
            <match_result>
                <Winner>
                    <team_name team_info="T1">Man City</team_name>
                    <manager>Josep Guardiola</manager>
                    <strategy>4-2-3-1</strategy>
                    <starting_list>
                        <match_player num = "31" position="Goalkeeper" />
                        <match_player num = "2" position="Defender" captain = "yes" />
                        <match_player num = "3" position="Defender" />
                        <match_player num = "5" position="Defender"/>
                        <match_player num = "24" position="Defender"/>
                        <match_player num = "10" position="Midfielder"/>
                        <match_player num = "16" position="Midfielder"/>
                        <match_player num = "19" position="Midfielder"/>
                        <match_player num = "20" position="Midfielder"/>
                        <match_player num = "47" position="Midfielder" goal = "1" />
                        <match_player num = "9" position="Forward" goal = "2" />
                    </starting_list>
                    <substitutes>
                        <match_player num="8" position="Midfielder" replaced_num="19" />
                        <match_player num="11" position="Forward" replaced_num="10" />
                    </substitutes>
                </Winner>
                <Loser>
                    <team_name team_info="T2">Man Utd</team_name>
                    <manager>Erik ten Hag</manager>
                    <strategy>4-2-3-1</strategy>
                    <starting_list>
                        <match_player num = "24" position="Goalkeeper" />
                        <match_player num = "2" position="Defender" />
                        <match_player num = "5" position="Defender"/>
                        <match_player num = "20" position="Defender"/>
                        <match_player num = "35" position="Defender"/>
                        <match_player num = "4" position="Midfielder"/>
                        <match_player num = "8"  position="Midfielder" captain = "yes" />
                        <match_player num = "10" position="Midfielder"/>
                        <match_player num = "14" position="Midfielder"/>
                        <match_player num = "39" position="Midfielder"/>
                        <match_player num = "11" position="Forward"/>
                    </starting_list>
                    <substitutes>
                        <match_player num="15" position="Defender" replaced_num="2" />
                        <match_player num="9" position="Forward" replaced_num="10" />
                        <match_player num="17" position="Forward" replaced_num="11" />
                        <match_player num="21" position="Forward" replaced_num="14" />
                    </substitutes>
                </Loser>
            </match_result>
            <match_statistics>
                <!--                    Winner team:loser team-->
                <score>3:0</score>
                <Possession>60.5:39.5</Possession>
                <Shots_on_target>10:3</Shots_on_target>
                <Shots>21:7</Shots>
            </match_statistics>
        </match>
        <match match_no="M2">
            <match_info>
                <info>WOL vs LIV</info>
                <date week="5">2023-09-16</date>
            </match_info>
            <match_result>
                <Winner>
                    <team_name team_info="T3">Liverpool</team_name>
                    <manager>Jürgen Klopp</manager>
                    <strategy>4-3-3</strategy>
                    <starting_list>
                        <match_player num="1" position="Goalkeeper"/>
                        <match_player num="2" position="Defender"/>
                        <match_player num="26" position="Defender" goal="1" captain="yes"/>
                        <match_player num="32" position="Defender"/>
                        <match_player num="78" position="Defender"/>
                        <match_player num="8" position="Midfielder"/>
                        <match_player num="10" position="Midfielder"/>
                        <match_player num="17" position="Midfielder"/>
                        <match_player num="11" position="Forward"/>
                        <match_player num="18" position="Forward" goal="1"/>
                        <match_player num="20" position="Forward"/>
                    </starting_list>
                    <substitutes>
                        <match_player num="5" position="Defender" replaced_num="78"/>
                        <match_player num="19" position="Midfielder" replaced_num="20"/>
                        <match_player num="38" position="Midfielder" replaced_num="11"/>
                        <match_player num="7" position="Forward" replaced_num="10"/>
                        <match_player num="9" position="Forward" replaced_num="18"/>
                    </substitutes>
                </Winner>
                <Loser>
                    <team_name team_info="T4">Wolves</team_name>
                    <manager>Gary O'Neil</manager>
                    <strategy>4-2-3-1</strategy>
                    <starting_list>
                        <match_player num="1" position="Goalkeeper"/>
                        <match_player num="3" position="Defender"/>
                        <match_player num="15" position="Defender"/>
                        <match_player num="22" position="Defender"/>
                        <match_player num="23" position="Defender" captain="yes"/>
                        <match_player num="5" position="Midfielder"/>
                        <match_player num="7" position="Midfielder"/>
                        <match_player num="8" position="Midfielder"/>
                        <match_player num="11" position="Midfielder" goal="1"/>
                        <match_player num="27" position="Midfielder"/>
                        <match_player num="12" position="Forward"/>
                    </starting_list>
                    <substitutes>
                        <match_player num="2" position="Defender" replaced_num="11"/>
                        <match_player num="17" position="Defender" replaced_num="3" own_goal="1"/>
                        <match_player num="6" position="Midfielder" replaced_num="5"/>
                        <match_player num="20" position="Midfielder" replaced_num="27"/>
                        <match_player num="9" position="Forward" replaced_num="12"/>
                    </substitutes>
                </Loser>
            </match_result>
            <match_statistics>
                <score>1:3</score>
                <Possession>34.2:65.8</Possession>
                <Shots_on_target>2:6</Shots_on_target>
                <Shots>11:16</Shots>
            </match_statistics>
        </match>
        <match match_no="M3">
            <match_info>
                <info>TOT vs LIV</info>
                <date week="7">2023-10-01</date>
            </match_info>
            <match_result>
                <Winner>
                    <team_name team_info="T5">Spurs</team_name>
                    <manager>Ange Postecoglou</manager>
                    <strategy>4-2-3-1</strategy>
                    <starting_list>
                        <match_player num="13" position="Goalkeeper"/>
                        <match_player num="17" position="Defender"/>
                        <match_player num="23" position="Defender"/>
                        <match_player num="37" position="Defender"/>
                        <match_player num="38" position="Defender"/>
                        <match_player num="8" position="Midfielder"/>
                        <match_player num="9" position="Midfielder"/>
                        <match_player num="10" position="Midfielder"/>
                        <match_player num="21" position="Midfielder"/>
                        <match_player num="29" position="Midfielder"/>
                        <match_player num="7" position="Forward" captain="yes" goal="1"/>
                    </starting_list>
                    <substitutes>
                        <match_player num="33" position="Defender" replaced_num="38"/>
                        <match_player num="4" position="Midfielder" replaced_num="29"/>
                        <match_player num="5" position="Midfielder" replaced_num="8"/>
                        <match_player num="27" position="Forward" replaced_num="7"/>
                        <match_player num="36" position="Forward" replaced_num="10"/>
                    </substitutes>
                </Winner>
                <Loser>
                    <team_name team_info="T3">Liverpool</team_name>
                    <manager>Jürgen Klopp</manager>
                    <strategy>4-3-3</strategy>
                    <starting_list>
